apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pyhook
  namespace: ${SERVICE}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - patch
  - update
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pyhook
  namespace: ${SERVICE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pyhook
subjects:
- kind: ServiceAccount
  name: default
  namespace: pyhook
